### ISSUE TITLE
release.yml可能需要加入权限

### ISSUE THREAD

**Issue by Zacharia2** [tiddly-gittly/Modern.TiddlyDev#45]
```yml
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

```

在发布插件时发现没有这个无法正确推送工件。
